# 连接池配置
spring:
  neo4j:
    authentication:
      username: neo4j
      password: 123456789
    uri: bolt://localhost:7687


server:
  port: 8090

#jwt配置
jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: headline123456  #当前程序签名秘钥 自定义